name: test_drive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  flutter_animate: ^4.0.0
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/images/water1.jpg
    - assets/images/water2.jpg
    - assets/images/water3.jpg
    - assets/images/water4.jpg
    - assets/images/water5.jpg
    - assets/images/water6.jpg
    - assets/images/water7.jpg
    - assets/images/water8.jpg
    - assets/images/water9.jpg
    - assets/images/water-background.jpg
    - assets/images/logo.png